Repository np-guard/network-config-analyzer, pull requests merged in 2024-12, with the labels that each got.

#111 Restore testing on a live cluster
  .github/workflows/test-push.yml
Labels: size/M

#134 Tiny fix to README.md
  README.md
Labels: size/XS

#135 Add to Manifest a JavaScript file, needed for interactivity
  MANIFEST.in
Labels: size/XS

#136 update supported istio resources api version + small parser bug fix
  nca/NetworkConfig/PoliciesFinder.py
  nca/Parsers/IstioGatewayYamlParser.py
  nca/Parsers/IstioServiceEntryYamlParser.py
  nca/Parsers/IstioSidecarYamlParser.py
  nca/Parsers/IstioVirtualServiceYamlParser.py
Labels: size/S

#142 add collector script
  collector/collect.py
Labels: size/S

#143 Allow duplicate policies (ignore newer)
  nca/NetworkConfig/PoliciesFinder.py
Labels: size/XS

#144 Fix faulty file-path in warning
  nca/Parsers/GenericYamlParser.py
Labels: size/XS

#145 Include collector in network-config-analyzer package
  collector/__init__.py
  collector/collect.py
  setup.cfg
Labels: size/M

#146 version 2.1.0
  nca/VERSION.txt
Labels: size/XS
